//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.ApolloFederation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FederationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FederationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotChocolate.ApolloFederation.Properties.FederationResources", typeof(FederationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _Any scalar is used to pass representations of entities from external services into the root _entities field for execution. Validation of the _Any scalar is done by matching the __typename and @external fields defined in the schema..
        /// </summary>
        internal static string Any_Description {
            get {
                return ResourceManager.GetString("Any_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityResolver must be a method. Please check if the EntityResolverAttribute is correctly set to a method..
        /// </summary>
        internal static string EntityResolver_MustBeMethod {
            get {
                return ResourceManager.GetString("EntityResolver_MustBeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union of all types that key directive applied. This information is needed by the Apollo federation gateway..
        /// </summary>
        internal static string EntityType_Description {
            get {
                return ResourceManager.GetString("EntityType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive to indicate that a field is owned by another service, for example via Apollo federation..
        /// </summary>
        internal static string ExternalDirective_Description {
            get {
                return ResourceManager.GetString("ExternalDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string FieldDescriptorExtensions_Key_FieldSet_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("FieldDescriptorExtensions_Key_FieldSet_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string FieldDescriptorExtensions_Provides_FieldSet_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("FieldDescriptorExtensions_Provides_FieldSet_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string FieldDescriptorExtensions_Requires_FieldSet_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("FieldDescriptorExtensions_Requires_FieldSet_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar representing a set of fields..
        /// </summary>
        internal static string FieldsetType_Description {
            get {
                return ResourceManager.GetString("FieldsetType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to indicate a combination of fields that can be used to uniquely identify and fetch an object or interface..
        /// </summary>
        internal static string KeyDirective_Description {
            get {
                return ResourceManager.GetString("KeyDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to import an external schema..
        /// </summary>
        internal static string LinkDirective_Description {
            get {
                return ResourceManager.GetString("LinkDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to annotate the expected returned fieldset from a field on a base type that is guaranteed to be selectable by the federation gateway..
        /// </summary>
        internal static string ProvidesDirective_Description {
            get {
                return ResourceManager.GetString("ProvidesDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to annotate the required input fieldset from a base type for a resolver..
        /// </summary>
        internal static string RequiresDirective_Description {
            get {
                return ResourceManager.GetString("RequiresDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression must refer to a method representing the reference resolver..
        /// </summary>
        internal static string ResolveReference_MustBeMethod {
            get {
                return ResourceManager.GetString("ResolveReference_MustBeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type provides a field named sdl: String! which exposes the SDL of the service&apos;s schema. This SDL (schema definition language) is a printed version of the service&apos;s schema including the annotations of federation directives. This SDL does not include the additions of the federation spec..
        /// </summary>
        internal static string ServiceType_Description {
            get {
                return ResourceManager.GetString("ServiceType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given any representation has an invalid format..
        /// </summary>
        internal static string ThrowHelper_Any_HasInvalidFormat {
            get {
                return ResourceManager.GetString("ThrowHelper_Any_HasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The apollo gateway tries to resolve an entity for which no EntityResolver method was found..
        /// </summary>
        internal static string ThrowHelper_EntityResolver_NoEntityResolverFound {
            get {
                return ResourceManager.GetString("ThrowHelper_EntityResolver_NoEntityResolverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema has no types with a KeyDirective and therefor no entities. Apollo federation requires at least on entity..
        /// </summary>
        internal static string ThrowHelper_EntityType_NoEntities {
            get {
                return ResourceManager.GetString("ThrowHelper_EntityType_NoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fieldset has an invalid format..
        /// </summary>
        internal static string ThrowHelper_FieldSet_HasInvalidFormat {
            get {
                return ResourceManager.GetString("ThrowHelper_FieldSet_HasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key attribute is used on `{0}` without specifying the the field set..
        /// </summary>
        internal static string ThrowHelper_Key_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Key_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldSet is null or empty on type.
        /// </summary>
        internal static string ThrowHelper_Provides_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Provides_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldSet is null or empty on type.
        /// </summary>
        internal static string ThrowHelper_Requires_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Requires_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot parse the given value of type `{1}`.
        /// </summary>
        internal static string ThrowHelper_Scalar_CannotParseValue {
            get {
                return ResourceManager.GetString("ThrowHelper_Scalar_CannotParseValue", resourceCulture);
            }
        }
    }
}
